# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AA5G5MEoa5qYdUXqIDEGJpqo4zbSCNcI
"""

import statistics
data = [1, 5, 3, 9, 7, 8, 2, 4, 6,]

mean = statistics.mean(data)
print (" Median:",mean)

median = statistics.median(data)
print (" Median:",median)

mode = statistics.mode(data)
print (" Median:",mode)

variance = statistics.variance(data)
print (" variance:",variance)

std_deviation=statistics.stdev(data)
print (" std_deviation:",std_deviation)